# Generated by Django 3.2.7 on 2021-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='type',
            field=models.CharField(default='Sale', max_length=10),
            preserve_default=False,
        ),
    ]
